- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "AWS DEVSecOP"
    DURATION: "140HR"
    TRAINER: "SHIVA"
  tasks:
   - name: print variables
     vars:
      COURSE: Ansible
     ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Trainer is: {{ TRAINER }}"